apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: airton-ads
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: airton-ads/booking-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: booking-db-secrets
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: booking-db-secrets
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: booking-db-secrets
              key: password
        - name: GOOGLE_CALENDAR_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: google-api-secrets
              key: calendar-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: airton-ads
spec:
  selector:
    app: booking-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP