apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: airton-ads
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: airton-ads/notification-service:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.3"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: GMAIL_API_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: google-api-secrets
              key: gmail-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: airton-ads
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP