apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: airton-ads
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: airton-ads/payment-service:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: mongodb-uri
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: stripe-webhook-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: airton-ads
spec:
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP