name: Deploy Vitrine Climatisation Airton ADS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Définition des permissions minimales globales
permissions:
  contents: read

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
    
    - name: Lint Frontend
      id: lint-frontend
      run: |
        cd frontend
        npm run lint
      continue-on-error: true
    
    - name: Retry Lint Frontend on failure
      if: steps.lint-frontend.outcome == 'failure'
      run: |
        cd frontend
        npm run lint
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    - name: Build Backend
      run: |
        cd backend
        npm run build
    
    - name: Run Tests
      id: run-tests
      run: |
        cd frontend
        npm test -- --watchAll=false
        cd ../backend
        npm test
      continue-on-error: true
    
    - name: Retry Tests on failure
      if: steps.run-tests.outcome == 'failure'
      run: |
        cd frontend
        npm test -- --watchAll=false
        cd ../backend
        npm test
    
    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          frontend/build
          backend/dist
        retention-days: 30

  deploy_staging:
    name: Deploy to Staging
    needs: build_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: staging
      url: 'https://staging.airton-installation.fr'
    
    # Permissions spécifiques pour le job de déploiement
    permissions:
      contents: read
      id-token: write  # Pour l'authentification OIDC si nécessaire
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/airton-frontend:staging
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and Push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/airton-backend:staging
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to Staging
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        script: |
          cd /opt/airton-installation
          docker-compose -f docker-compose.staging.yml pull
          docker-compose -f docker-compose.staging.yml up -d
    
    - name: Verify Deployment
      run: |
        # Attente de 30 secondes pour que le service démarrage
        sleep 30
        # Vérification que le service répond avec un statut 200
        curl -s -o /dev/null -w "%{http_code}" https://staging.airton-installation.fr/health | grep 200
      continue-on-error: true

  deploy_production:
    name: Deploy to Production
    needs: deploy_staging
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: 'https://airton-installation.fr'
    
    # Permissions spécifiques pour le job de déploiement
    permissions:
      contents: read
      id-token: write  # Pour l'authentification OIDC si nécessaire
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag and Push Docker images for Production
      run: |
        docker pull ${{ secrets.DOCKER_REGISTRY }}/airton-frontend:staging
        docker pull ${{ secrets.DOCKER_REGISTRY }}/airton-backend:staging
        docker tag ${{ secrets.DOCKER_REGISTRY }}/airton-frontend:staging ${{ secrets.DOCKER_REGISTRY }}/airton-frontend:production
        docker tag ${{ secrets.DOCKER_REGISTRY }}/airton-backend:staging ${{ secrets.DOCKER_REGISTRY }}/airton-backend:production
        docker push ${{ secrets.DOCKER_REGISTRY }}/airton-frontend:production
        docker push ${{ secrets.DOCKER_REGISTRY }}/airton-backend:production
    
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          cd /opt/airton-installation
          docker-compose -f docker-compose.production.yml pull
          docker-compose -f docker-compose.production.yml up -d
    
    - name: Verify Deployment
      run: |
        # Attente de 30 secondes pour que le service démarrage
        sleep 30
        # Vérification que le service répond avec un statut 200
        curl -s -o /dev/null -w "%{http_code}" https://airton-installation.fr/health | grep 200
      continue-on-error: true
    
    - name: Send Deployment Notification
      uses: rtCamp/action-slack-notify@v2.2.1
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_COLOR: good
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_TITLE: Production Deployment Completed
        SLACK_MESSAGE: 'Vitrine Climatisation Airton ADS has been successfully deployed to production!'
        SLACK_FOOTER: 'CI/CD Pipeline'

  monitoring_setup:
    name: Setup Monitoring
    needs: deploy_production
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    # Permissions minimales pour le job de monitoring
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Monitoring Tools
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          cd /opt/airton-installation/monitoring
          docker-compose up -d
    
    # Ajout d'une vérification des métriques de base
    - name: Verify Monitoring
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PRODUCTION_HOST }}
        username: ${{ secrets.PRODUCTION_USERNAME }}
        key: ${{ secrets.PRODUCTION_SSH_KEY }}
        script: |
          # Vérification que Prometheus est en cours d'exécution
          if docker ps | grep prometheus; then
            echo "Prometheus monitoring is running properly"
          else
            echo "Prometheus monitoring failed to start"
            exit 1
          fi