name: "Gestion des Issues Inactives"

on:
  schedule:
    # Exécution tous les jours à minuit
    - cron: '0 0 * * *'
  workflow_dispatch:  # Permet de déclencher manuellement

# Définition des autorisations minimales nécessaires
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Étiqueter et fermer les issues et PR inactives
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Identifier et gérer les éléments inactifs
      uses: actions/stale@v9
      with:
        # Configuration générale
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 14
        operations-per-run: 100
        remove-stale-when-updated: true
        ascending: true
        
        # Configuration pour les issues
        stale-issue-message: |
          Cette issue a été automatiquement marquée comme inactive car elle n'a pas eu d'activité récente depuis 30 jours.
          
          Elle sera fermée dans 14 jours si aucune activité supplémentaire n'a lieu. Si vous pensez que cette issue est toujours pertinente et nécessite attention, veuillez laisser un commentaire.
          
          Merci pour votre compréhension et votre contribution au projet.
        
        close-issue-message: |
          Cette issue a été automatiquement fermée car elle est restée inactive pendant 14 jours après avoir été marquée comme inactive.
          
          Si vous pensez que cette fermeture est incorrecte ou que le problème persiste, n'hésitez pas à rouvrir l'issue ou à créer une nouvelle issue avec une référence à celle-ci.
          
          Merci pour votre compréhension et votre contribution au projet.
        
        stale-issue-label: 'inactive'
        close-issue-label: 'fermée-par-bot'
        exempt-issue-labels: 'bug,enhancement,documentation,security,pinned,à-garder'
        
        # Configuration pour les pull requests
        stale-pr-message: |
          Cette pull request a été automatiquement marquée comme inactive car elle n'a pas eu d'activité récente depuis 30 jours.
          
          Elle sera fermée dans 14 jours si aucune activité supplémentaire n'a lieu. Si vous travaillez toujours sur cette PR, veuillez laisser un commentaire ou pousser de nouveaux commits.
          
          Merci pour votre compréhension et votre contribution au projet.
        
        close-pr-message: |
          Cette pull request a été automatiquement fermée car elle est restée inactive pendant 14 jours après avoir été marquée comme inactive.
          
          Si vous souhaitez toujours que ces changements soient fusionnés, n'hésitez pas à rouvrir la PR ou à créer une nouvelle PR avec une référence à celle-ci.
          
          Merci pour votre compréhension et votre contribution au projet.
        
        stale-pr-label: 'inactive'
        close-pr-label: 'fermée-par-bot'
        exempt-pr-labels: 'work-in-progress,security,pinned,à-garder'
        exempt-draft-pr: true
        
        # Configuration par language
        any-of-labels: 'bug,enhancement,documentation,question'
        exempt-all-milestones: true
        
    # Rapport d'activité
    - name: Générer un rapport d'activité hebdomadaire
      if: github.event_name == 'schedule' && (github.event.schedule == '0 0 * * 1')  # Uniquement le lundi
      run: |
        echo "## Rapport hebdomadaire de gestion des issues inactives" > stale-report.md
        echo "Date: $(date)" >> stale-report.md
        echo "" >> stale-report.md
        
        # Obtenir les statistiques via l'API GitHub
        TOKEN="${{ secrets.GITHUB_TOKEN }}"
        REPO="${{ github.repository }}"
        
        # Compter les issues par état et label
        OPEN_ISSUES=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/issues?state=open&per_page=1" | jq -r 'first(..|.total_count? // empty) // 0')
        STALE_ISSUES=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/search/issues?q=repo:$REPO+label:inactive+state:open+is:issue" | jq -r '.total_count')
        CLOSED_ISSUES_WEEK=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/search/issues?q=repo:$REPO+label:fermée-par-bot+closed:>$(date -d '7 days ago' +'%Y-%m-%d')+is:issue" | jq -r '.total_count')
        
        echo "### Issues" >> stale-report.md
        echo "- Issues ouvertes: $OPEN_ISSUES" >> stale-report.md
        echo "- Issues marquées comme inactives: $STALE_ISSUES" >> stale-report.md
        echo "- Issues fermées cette semaine pour inactivité: $CLOSED_ISSUES_WEEK" >> stale-report.md
        echo "" >> stale-report.md
        
        # Compter les PRs par état et label
        OPEN_PRS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/search/issues?q=repo:$REPO+is:pr+state:open" | jq -r '.total_count')
        STALE_PRS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/search/issues?q=repo:$REPO+label:inactive+state:open+is:pr" | jq -r '.total_count')
        CLOSED_PRS_WEEK=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/search/issues?q=repo:$REPO+label:fermée-par-bot+closed:>$(date -d '7 days ago' +'%Y-%m-%d')+is:pr" | jq -r '.total_count')
        
        echo "### Pull Requests" >> stale-report.md
        echo "- PRs ouvertes: $OPEN_PRS" >> stale-report.md
        echo "- PRs marquées comme inactives: $STALE_PRS" >> stale-report.md
        echo "- PRs fermées cette semaine pour inactivité: $CLOSED_PRS_WEEK" >> stale-report.md
        
        cat stale-report.md
        
    - name: Sauvegarder le rapport
      if: github.event_name == 'schedule' && (github.event.schedule == '0 0 * * 1')  # Uniquement le lundi
      uses: actions/upload-artifact@v4
      with:
        name: stale-issues-report
        path: stale-report.md
        retention-days: 90